### ISSUE TITLE
Version 1.0.0 roadmap

### ISSUE THREAD

**Issue by michalkvasnicak** [Byteclaw/visage#492]
## Functionality

- ~#349 - mechanism to implement focus-visible on all focusable elements~ for now removed from 1.0, there is not 100% reliable polyfill for this
- [ ] - #327 - scroll lock manager
- [x] - #310 - subtle focus styles for `Link`
- [x] - #488 - ~`InlineMessage` component~ inverted `Message` variant
- [ ] - #474 - fix blur on Menu
- [x] - #368 - default theme for quick project bootstrap
- [ ] - #198 - menu scroll bug
- [x] - #517 - do not close underlying layers if AutocompleteInput/Select is expanded.
- [x] - #77  - `Tooltip` component
- [x] - #526 - `Popper` component

## Refactor

- [ ] - #397 - move pseudostyles to mixins
- [ ] - #389 - box shadows as constants in theme
- [x] - #417 - clean up dependencies and add peer deps where possible

## Documentation

- [ ] - #482 - landing page 
- [x] - #399 - faces
- [x] - #468 - accessibility sections
- [x] - #398 - variants and variant creators
- [ ] - #299 - browser compatibility
